// The FAQ shown on each course page AND declared in its FAQPage schema.
//
// These lived in two places - the schema in layout.tsx and a shorter hand-written set in
// PageContent.tsx. The counts matched but the wording had drifted, so every answer the
// schema promised was absent from the rendered page. Measured 2026-09-18: 0 of 59 course
// FAQ answers were present in the server HTML. One array now feeds both.

export type CourseFaq = { q: string; a: string };

export const COURSE_FAQS: Record<string, readonly CourseFaq[]> = {
  "cardiac-technology": [
    { q: "What is Bachelor of Science in Cardiac Technology at JKKN College Tamil Nadu?", a: "Bachelor of Science in Cardiac Technology is a four-year allied health science degree training professionals in cardiovascular diagnosis using electrocardiogram, echocardiography, and cardiac catheterization." },
    { q: "What are the eligibility requirements for Bachelor of Science Cardiac Technology in Tamil Nadu?", a: "Candidates need Plus Two with Physics, Chemistry, and Biology with minimum 50 percent aggregate marks. Scheduled Caste and Scheduled Tribe candidates need 40 percent." },
    { q: "What is the career scope of Cardiac Technology after graduation in India?", a: "Cardiac Technology graduates work in hospitals, catheterization labs, rehabilitation centers, and medical device companies in electrocardiogram, echocardiography, and interventional cardiology roles." },
    { q: "What are the career opportunities after Bachelor of Science Cardiac Technology?", a: "Graduates work as Cardiovascular Technologists, Echocardiogram Technicians, Catheterization Lab Technicians, Pacemaker Technicians, and Application Specialists in hospitals." },
    { q: "Can I pursue higher education after Bachelor of Science Cardiac Technology?", a: "Yes, graduates can pursue Master of Science in Cardiac Technology, public health, or hospital administration specializations for advanced career opportunities." },
  ],
  "dialysis-technology": [
    { q: "What is Bachelor of Science in Dialysis Technology at JKKN College Tamil Nadu?", a: "Bachelor of Science in Dialysis Technology is a four-year degree training professionals in hemodialysis, peritoneal dialysis, and renal replacement therapy at JKKN College." },
    { q: "What are the eligibility requirements for Bachelor of Science Dialysis Technology in Tamil Nadu?", a: "Candidates need Plus Two with Physics, Chemistry, and Biology with minimum 50 percent aggregate marks. Scheduled Caste and Scheduled Tribe need 40 percent." },
    { q: "What is the salary of a Dialysis Technologist in India?", a: "Entry-level dialysis technologists earn two to four lakhs per annum. With experience, salaries range from five to twenty lakhs depending on position and hospital." },
    { q: "What are the career opportunities after Bachelor of Science Dialysis Technology?", a: "Graduates work as Dialysis Technicians, Hemodialysis Specialists, Renal Care Coordinators, and Dialysis Unit Supervisors in hospitals and dialysis centers." },
    { q: "Can I pursue higher education after Bachelor of Science Dialysis Technology?", a: "Yes, graduates can pursue Master of Science in Dialysis Technology, Renal Sciences, or Healthcare Management for advanced career opportunities." },
    { q: "What practical training is included in the Dialysis Technology program at JKKN?", a: "The program includes over two thousand hours of clinical training in hemodialysis units, peritoneal dialysis centers, and nephrology departments with hands-on experience." },
    { q: "Is there demand for Dialysis Technologists in India?", a: "Yes, India has over two lakh patients needing regular dialysis, with demand growing annually due to rising diabetes and kidney disease cases." },
    { q: "What is the difference between Hemodialysis and Peritoneal Dialysis?", a: "Hemodialysis uses an external machine to filter blood at a center. Peritoneal dialysis uses the abdominal membrane as a natural filter and can be done at home." },
  ],
  "radiology-imaging-technology": [
    { q: "What is Bachelor of Science Radiography Imaging Technology at JKKN College of Allied Health Sciences in Komarapalayam?", a: "Bachelor of Science Radiography Imaging Technology is a three-year plus one-year internship undergraduate program training learners in X-ray, Computed Tomography, Magnetic Resonance Imaging, and ultrasound diagnostic imaging." },
    { q: "What is the eligibility criteria for Bachelor of Science Radiography Imaging Technology at JKKN Allied Health Sciences Komarapalayam?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks. Scheduled Caste and Scheduled Tribe: 40%. Other Backward Classes: 45%. Age minimum 17 years." },
    { q: "What is the salary after completing Bachelor of Science Radiography Imaging Technology from JKKN College Komarapalayam Tamil Nadu?", a: "Entry-level radiology technologists earn three to five lakhs per year. Experienced Computed Tomography and Magnetic Resonance Imaging specialists at corporate hospitals earn twelve to twenty lakhs annually." },
    { q: "What are the career opportunities after Bachelor of Science Radiography Imaging Technology from JKKN Allied Health Sciences in Tamil Nadu?", a: "Graduates work as X-ray Technician, Computed Tomography Technologist, Magnetic Resonance Imaging Technologist, Ultrasound Technician, Mammography Specialist, and Interventional Radiology Technician in hospitals." },
    { q: "Is Bachelor of Science Radiography Imaging Technology at JKKN College of Allied Health Sciences Komarapalayam a good career choice?", a: "Yes. Growing healthcare demand, advanced imaging technology, competitive salaries, and diverse specializations make Bachelor of Science Radiography Imaging Technology an excellent career choice in Tamil Nadu." },
    { q: "Can I pursue higher education after Bachelor of Science Radiography Imaging Technology from JKKN Allied Health Sciences Tamil Nadu?", a: "Yes. Graduates can pursue Master of Science in Radiography, Medical Imaging, or Radiological Sciences. Postgraduate Diploma in Computed Tomography or Magnetic Resonance Imaging technology is also available." },
    { q: "What practical training is included in Bachelor of Science Radiography Imaging Technology at JKKN College Komarapalayam?", a: "The program includes over two thousand hours of clinical training covering X-ray, Computed Tomography, Magnetic Resonance Imaging, ultrasound, mammography, and radiation safety in hospital radiology departments." },
    { q: "Is radiation exposure a concern for Radiography Imaging Technology learners at JKKN Allied Health Sciences in Tamil Nadu?", a: "No. Strict safety protocols, protective equipment, and As Low As Reasonably Achievable radiation principles keep exposure minimal. Technologists receive thorough radiation safety training before clinical practice." },
  ],
  "operation-theatre-anaesthesia": [
    { q: "What is Bachelor of Science Operation Theatre and Anaesthesia Technology at JKKN College Tamil Nadu?", a: "It is a four-year undergraduate degree at JKKN College Tamil Nadu training learners in surgical assistance, anaesthesia support, patient monitoring, sterilization, and perioperative care management." },
    { q: "What is the eligibility criteria for Bachelor of Science Operation Theatre and Anaesthesia Technology at JKKN College Tamil Nadu?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks (40% for Scheduled Caste and Scheduled Tribe, 45% for Other Backward Classes), and must be 17 years or older." },
    { q: "What is the salary of an Operation Theatre technician after studying at JKKN College Tamil Nadu?", a: "Entry-level Operation Theatre technicians earn 3 to 5 lakhs per year. With experience, salaries reach 10 to 20 lakhs. International placements offer higher remuneration." },
    { q: "What are the career opportunities after Bachelor of Science Operation Theatre and Anaesthesia Technology at JKKN College Tamil Nadu?", a: "Graduates work as Operation Theatre Technicians, Anaesthesia Technicians, Surgical Assistants, Central Sterile Supply Department Technicians, Endoscopy Technicians, and Intensive Care Unit Technicians." },
    { q: "What is the scope of Operation Theatre Technology in India for JKKN College Tamil Nadu graduates?", a: "Skilled Operation Theatre and anaesthesia technologists are in high demand across government hospitals, private healthcare chains, and international facilities due to rapid healthcare sector growth." },
    { q: "Can I pursue higher education after Bachelor of Science Operation Theatre and Anaesthesia Technology at JKKN College Tamil Nadu?", a: "Yes, graduates can pursue Master of Science in Operation Theatre and Anaesthesia Technology, Critical Care, Post Graduate Diploma in Surgical Technology, or an MBA in Healthcare Management." },
    { q: "What practical training is included in Bachelor of Science Operation Theatre and Anaesthesia Technology at JKKN College Tamil Nadu?", a: "The program provides 2000 plus hours of clinical training in operation theatres, anaesthesia departments, Central Sterile Supply Department units, and Intensive Care Units with hands-on surgical experience." },
    { q: "What is the difference between Operation Theatre Technician and Anaesthesia Technician at JKKN College Tamil Nadu?", a: "Operation Theatre Technicians assist surgeons and manage instruments. Anaesthesia Technicians support anaesthesiologists, prepare equipment, and monitor patients. JKKN's program trains graduates in both specializations." },
  ],
  "respiratory-therapy": [
    { q: "What is Bachelor of Science Respiratory Therapy and what does it involve at JKKN College Tamil Nadu?", a: "Bachelor of Science Respiratory Therapy at JKKN College Tamil Nadu is a four-year program training learners in pulmonary diagnostics, mechanical ventilation, airway management, and cardiopulmonary rehabilitation." },
    { q: "What is the eligibility criteria for Bachelor of Science Respiratory Therapy at JKKN College Tamil Nadu?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks (40% for Scheduled Caste and Scheduled Tribe, 45% for Other Backward Classes), and age 17 years or older." },
    { q: "What is the salary of a Respiratory Therapist in India after JKKN College Tamil Nadu?", a: "Entry-level respiratory therapists earn 3 to 5 lakhs per year. With experience and critical care specialization, salaries range from 6 to 12 lakhs. Senior positions offer 15 to 25 lakhs annually." },
    { q: "What are the career opportunities after Bachelor of Science Respiratory Therapy at JKKN College Tamil Nadu?", a: "Graduates work as Respiratory Therapists, Intensive Care Unit Ventilator Specialists, Pulmonary Function Technologists, Sleep Lab Technicians, and Neonatal Respiratory Care Specialists in hospitals and rehabilitation centers." },
    { q: "Can I pursue higher education after Bachelor of Science Respiratory Therapy at JKKN College Tamil Nadu?", a: "Yes, graduates can pursue Master of Science in Respiratory Therapy, Critical Care Technology, MBA in Healthcare Management, or international Registered Respiratory Therapist certification from the National Board for Respiratory Care." },
    { q: "What is the difference between Respiratory Therapy and Pulmonology for learners at JKKN College Tamil Nadu?", a: "Pulmonology requires an MBBS degree to independently diagnose lung diseases. Respiratory Therapy trains allied health professionals to manage ventilators and administer treatments under physician supervision." },
    { q: "Is Bachelor of Science Respiratory Therapy a good career choice at JKKN College Tamil Nadu?", a: "Yes, rising respiratory diseases and growing critical care demand make respiratory therapy an excellent career offering job stability, competitive salaries, and international opportunities for JKKN College graduates." },
    { q: "What practical training is included in Bachelor of Science Respiratory Therapy at JKKN College Tamil Nadu?", a: "The program provides over 1500 hours of clinical training in pulmonary function labs, Intensive Care Units, sleep labs, and neonatal units covering ventilator operation, airway management, and arterial blood gas analysis." },
  ],
  "physician-assistant": [
    { q: "What is the Bachelor of Science Physician Assistant course at JKKN College Tamil Nadu?", a: "The Bachelor of Science Physician Assistant course at JKKN College Tamil Nadu is a three-year degree plus one-year internship that trains learners to assist physicians in clinical diagnosis, treatment, and patient care." },
    { q: "What is the eligibility to join the Bachelor of Science Physician Assistant program at JKKN College Tamil Nadu?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks. Scheduled Caste and Scheduled Tribe candidates need 40%, Other Backward Classes candidates need 45%. Minimum age is 17 years." },
    { q: "What is the salary of a Physician Assistant graduate from JKKN College Tamil Nadu?", a: "Entry-level Physician Assistant graduates earn three to five lakhs per year. Experienced professionals earn six to ten lakhs. Senior roles in corporate hospitals offer twelve to twenty lakhs per year." },
    { q: "What career opportunities are available after the Bachelor of Science Physician Assistant course at JKKN College Tamil Nadu?", a: "Graduates work as Clinical Physician Assistants, Emergency Care Assistants, Surgical Assistants, Intensive Care Unit Assistants, Outpatient Department Coordinators, and Community Health Officers in hospitals and clinics." },
    { q: "Is the Bachelor of Science Physician Assistant course at JKKN College Tamil Nadu a good career choice?", a: "Yes. Growing demand for mid-level healthcare providers, competitive salaries, diverse roles, and India's expanding healthcare infrastructure make Physician Assistant an excellent career choice." },
    { q: "Can I pursue higher studies after the Bachelor of Science Physician Assistant course at JKKN College Tamil Nadu?", a: "Yes. Graduates can pursue Master of Science in Physician Assistant Studies, Master of Science in Clinical Medicine, Master of Public Health, or a Master of Business Administration in Healthcare Management." },
    { q: "What practical training is included in the Bachelor of Science Physician Assistant course at JKKN College Tamil Nadu?", a: "The program includes over two thousand hours of clinical training across outpatient departments, emergency departments, Intensive Care Units, operation theatres, and community health settings." },
    { q: "What is the difference between a Physician Assistant and a doctor at JKKN College Tamil Nadu?", a: "Physician Assistants practice under physician supervision and assist in diagnosis and treatment. Doctors hold independent practice rights and complete five and a half years of MBBS training." },
  ],
  "critical-care-technology": [
    { q: "What is the Bachelor of Science Critical Care Technology course at JKKN College Tamil Nadu?", a: "The Bachelor of Science Critical Care Technology course at JKKN College Tamil Nadu is a four-year program training learners in Intensive Care Unit management, ventilator support, hemodynamic monitoring, and emergency care." },
    { q: "What is the eligibility to join the Bachelor of Science Critical Care Technology program at JKKN College Tamil Nadu?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks. Scheduled Caste and Scheduled Tribe candidates need 40%, Other Backward Classes candidates need 45%. Minimum age is 17 years." },
    { q: "What is the salary of a Critical Care Technology graduate from JKKN College Tamil Nadu?", a: "Entry-level critical care technologists earn three to five lakhs per year. With experience, salaries reach six to twelve lakhs. Senior Intensive Care Unit roles in corporate hospitals offer fifteen to twenty-five lakhs annually." },
    { q: "What career opportunities are available after the Bachelor of Science Critical Care Technology course at JKKN College Tamil Nadu?", a: "Graduates work as Intensive Care Unit Technicians, Ventilator Technicians, Emergency Care Specialists, Respiratory Therapists, and Critical Care Coordinators in hospitals, trauma centers, and dialysis centers." },
    { q: "Can I pursue higher studies after the Bachelor of Science Critical Care Technology course at JKKN College Tamil Nadu?", a: "Yes. Graduates can pursue Master of Science in Critical Care Technology, Emergency Medicine, or Respiratory Care, or a Postgraduate Diploma in Critical Care and Master of Business Administration in Healthcare Management." },
    { q: "What practical training is included in the Bachelor of Science Critical Care Technology course at JKKN College Tamil Nadu?", a: "The program includes over two thousand hours of clinical training in Intensive Care Units, Coronary Care Units, emergency departments, dialysis units, neonatal and paediatric Intensive Care Units, and trauma care centers." },
  ],
  "medical-record-science": [
    { q: "What is Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Bachelor of Science Medical Record Science at JKKN College Tamil Nadu is a four-year degree training professionals in Health Information Management, medical coding, International Classification of Diseases, and hospital information systems." },
    { q: "What is the eligibility to join Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks. Scheduled Caste and Scheduled Tribe learners need 40%, Other Backward Classes learners need 45%. Minimum age is 17 years." },
    { q: "What salary can I earn after Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Entry-level Medical Record Science professionals earn 2.5 to 4 lakhs per year. Experienced Health Information Management specialists earn 5 to 12 lakhs. Senior roles in corporate hospitals pay up to 20 lakhs annually." },
    { q: "What career opportunities are available after Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Graduates work as Medical Record Technicians, Health Information Managers, Medical Coders, Clinical Data Analysts, and Healthcare Information Technology Specialists in hospitals, insurance companies, and pharmaceutical firms." },
    { q: "Is medical coding using International Classification of Diseases taught in Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Yes, International Classification of Diseases coding and Electronic Medical Records are core components. Learners learn disease classification, procedural coding, and hands-on practice with real medical records and coding software." },
    { q: "Can I work abroad after completing Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Yes, Health Information Management professionals are globally in demand. USA, UK, Canada, Australia, and Gulf nations hire trained medical coders. Additional international certifications further increase overseas job opportunities." },
    { q: "Can I pursue Master of Science after Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "Yes, graduates can pursue Master of Science in Medical Record Science or Health Informatics, or an MBA in Healthcare Management. Professional certifications in coding specialization are also available for career advancement." },
    { q: "What practical training is included in Bachelor of Science Medical Record Science at JKKN College Tamil Nadu?", a: "The program includes over 2000 hours of practical training in medical record departments, coding laboratories, Electronic Medical Records systems, and hospital internships with hands-on Health Information Management experience." },
  ],
  "accident-emergency-care": [
    { q: "What is Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu is a four-year degree training professionals in Emergency Medical Services, trauma care, Advanced Cardiac Life Support, disaster management, and emergency response coordination." },
    { q: "What is the eligibility to join Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "Candidates need 10+2 with Physics, Chemistry, and Biology, minimum 50% marks. Scheduled Caste and Scheduled Tribe learners need 40%, Other Backward Classes learners need 45%. Minimum age is 17 years. A medical fitness certificate is required." },
    { q: "What salary can I earn after Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "Entry-level emergency care technologists earn 3 to 5 lakhs per year. With three to five years experience, salaries reach 6 to 10 lakhs. Senior Emergency Room and disaster management positions pay up to 20 lakhs annually." },
    { q: "What career opportunities are available after Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "Graduates work as Emergency Medical Technicians, Trauma Care Specialists, Critical Care Technologists, Disaster Management Coordinators, Emergency Room Technicians, and Ambulance Service Managers in hospitals and trauma centers." },
    { q: "What certifications are provided in Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "Learners receive Basic Life Support and Advanced Cardiac Life Support certifications. The program also covers Advanced Trauma Life Support and Pediatric Advanced Life Support, making graduates highly qualified for emergency care positions." },
    { q: "Can I pursue Master of Science after Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "Yes, graduates can pursue Master of Science in Emergency Medicine, Critical Care, or Disaster Management. MBA in Healthcare Management and specialized Emergency Medical Services certifications are also available for advancement." },
    { q: "What practical training is included in Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu?", a: "The program includes over 2000 hours of clinical training in emergency departments, trauma centers, ambulance services, and disaster management units with hands-on patient assessment, triage, and Advanced Cardiac Life Support experience." },
    { q: "Is Bachelor of Science Accident and Emergency Care Technology at JKKN College Tamil Nadu a physically demanding career?", a: "Yes, Accident and Emergency Care requires physical stamina, quick thinking, and emotional resilience. Training includes physical fitness preparation for high-stress situations, long shifts, and physically demanding emergency care tasks." },
  ],
};
